webcam:
  timelapseEnabled: false
  webcamEnabled: false
plugins:
  DisplayLayerProgress:
    showAllPrinterMessages: false
    showHeightInStatusBar: false
    showLayerInStatusBar: false
    showOnBrowserTitle: false
    showOnNavBar: false
    showOnPrinterDisplay: true
  thespaghettidetective:
    auth_token: b7588cf3a16c787c7203
    sentry_opt: in
serial:
  autoconnect: true                                                                                                                     
  baudrate: 0                                                                                                                           
  port: AUTO
