FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:build

ENV UDEV=1

RUN python -m pip install --no-cache-dir OctoPrint

RUN python -m pip install --no-cache-dir \
    "https://github.com/marian42/octoprint-preheat/archive/master.zip" \
    "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/latest/download/master.zip" \
    "https://github.com/malnvenshorn/OctoPrint-FilamentManager/archive/master.zip" \
    "https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip"

# Seed the initial config.yaml
COPY ./config.yaml /root/.octoprint/config.yaml

CMD ["octoprint","serve","--iknowwhatimdoing","--host","0.0.0.0"]
